---
name: Lint Code Base
on:
  push:
    branches: [develop]
  workflow_dispatch:

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install package
        run: yarn install
      - name: spelling
        run: yarn spelling:ci ./src
      - name: eslint
        run: yarn eslint:ci ./src
      - name: prettier
        run: yarn prettier:ci ./src
      # - name: test
      #   run: yarn test

    env:
      CI: true
