---
name: Lint Code Base
on:
  push:
    branches: [develop]
  workflow_dispatch:

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install package
        run: npm install
      - name: spelling
        run: npm spelling:ci .
      - name: eslint
        run: npm eslint:ci components containers controllers hooks pages services utils views
      - name: prettier
        run: npm prettier:ci components containers controllers hooks pages services utils views
      # - name: test
      #   run: npm test
      - name: build
        env:
          NODE_ENV: production
          NEXT_PUBLIC_GRAPHQL_URL: ${{ secrets.NEXT_PUBLIC_GRAPHQL_URL }}
          NEXT_PUBLIC_MAGIC_PK: ${{ secrets.NEXT_PUBLIC_MAGIC_PK }}
          MAGIC_SK: ${{ secrets.MAGIC_SK }}
        run: npm build
    env:
      CI: true
